[tool.black]
line-length = 99
target-version = ["py38"]
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.vscode
  | env
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
src_paths = ["coral_deeplab", "tests", "examples"]
line_length = 99
lines_after_imports = 2
force_single_line = true
force_sort_within_sections = true
order_by_type = true
