version: "3.8"  # 최신 Docker Compose 버전 사용

services:
  ai-training:
    build: .  # 현재 디렉터리의 Dockerfile로 이미지 빌드
    container_name: coral_deeplab_trainer  # 컨테이너 이름 (선택 사항)
    
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_REQUIRE_CUDA="cuda>=11.8 brand=tesla,driver>=520,driver<521"

    volumes:
      - .:/workspace  # 현재 폴더를 /workspace로 마운트
      - /mnt/d/merged_all:/mnt/d/merged_all  # 데이터셋 마운트

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4  # GPU 4개 할당
              capabilities: [gpu]

    # (선택) 포트 매핑 - 필요한 경우에만 활성화
    # ports:
    #   - "8888:8888"  # 예: Jupyter Notebook 접속용
    #   - "6006:6006"  # 예: TensorBoard 접속용
