name: Code formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: code-formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -U black isort flake8

    - name: Black
      run: black . --check --diff
    
    - name: Flake8
      run: flake8 ./coral_deeplab --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Isort
      run: isort . --check --diff
